version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
    timezone: Canada/Eastern
  allow:
    - dependency-type: "development"
  open-pull-requests-limit: 2
