npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: "${NPM_PUBLISH_TOKEN:-invalid}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  "@parcel/types@*":
    dependencies:
      "@parcel/core": "*"
  "@mdx-js/loader@*":
    peerDependenciesMeta:
      "webpack":
        optional: true
  "gatsby-plugin-gatsby-cloud@*":
    peerDependenciesMeta:
      "webpack":
        optional: true

logFilters:
  - pattern: "@tophat/commit-utils-website@workspace:gatsby provides react *"
    level: discard
  - pattern: "gatsby-* doesn't provide graphql"
    level: discard
  - pattern: "gatsby@* doesn't provide babel-eslint"
    level: discard

enableTransparentWorkspaces: false
