version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

  lint:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Run Linting
          command: yarn lint

  publish:
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with NPM Registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish New Package Version with Lerna
          command: yarn lerna-publish

workflows:
  version: 2
  build_lint_publish:
    jobs:
      - build
      - lint:
          requires:
            - build
      - publish:
          requires:
            - build
            - lint
          filters:
            branches:
              only:
                - master
