version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/workspace
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-v1-{{ checksum "yarn.lock" }}
            - deps-v1-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: deps-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Lint
          command: make lint
          when: always

      - run:
          name: Test
          command: make test
          when: always

      - store_artifacts:
          path: artifacts

      - persist_to_workspace:
          root: ./
          paths:
            - artifacts/
            - lib/
            - node_modules/
  deploy:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/workspace
    steps:
      - checkout

      - attach_workspace:
          at: ~/workspace

      - run:
          name: Deploy Package
          command: make deploy
  website:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo/website
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          name: Restore node_modules cache
          key: website-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          name: Save node_modules cache
          key: website-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - build/
  deploy_website:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo/website
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          name: Restore node_modules cache
          key: website-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: ./
      - add_ssh_keys:
          fingerprints:
            - "c8:59:1a:57:07:18:0f:77:8f:1c:5d:c5:5e:d6:38:65"
      - run:
          name: Setup git user and deploy website
          command: |
            git config --global user.email "circleci-commit-watch@users.noreply.github.com"
            git config --global user.name "CircleCI commit-watch"
            USE_SSH=true yarn publish-gh-pages

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - website
      - deploy_website:
          requires:
              - website
          filters:
            branches:
              only:
                - master
