version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          paths:
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .

  lint:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Run Linting
          command: yarn lint

  publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with NPM Registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish New Package Version with Lerna
          command: yarn lerna-publish
  website:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo/website
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          name: Restore node_modules cache
          key: website-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          name: Save node_modules cache
          key: website-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - build/
  deploy_website:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo/website
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          name: Restore node_modules cache
          key: website-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: ./
      - add_ssh_keys:
          fingerprints:
            - "63:5b:dd:90:02:09:0c:c1:e7:79:06:f2:99:d3:4c:02"
      - run:
          name: Setup git user and deploy website
          command: |
            git config --global user.email "circleci-commit-utils@users.noreply.github.com"
            git config --global user.name "CircleCI commit-utils"
            USE_SSH=true yarn publish-gh-pages

workflows:
  version: 2
  build_lint_publish:
    jobs:
      - build
      - lint:
          requires:
            - build
      - publish:
          requires:
            - build
            - lint
          filters:
            branches:
              only:
                - master
      - website
      - deploy_website:
          requires:
            - website
          filters:
            branches:
              only:
                - master

experimental:
  notify:
    branches:
      only:
        - master
