version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/workspace
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-v1-{{ checksum "yarn.lock" }}
            - deps-v1-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: deps-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Lint
          command: make lint
          when: always

      - store_artifacts:
          path: artifacts

      - persist_to_workspace:
          root: ./
          paths:
            - artifacts/
            - lib/
            - node_modules/
  deploy:
    docker:
      - image: circleci/node:8.11.1
    working_directory: ~/workspace
    steps:
      - checkout

      - attach_workspace:
          at: ~/workspace

      - run:
          name: Deploy Package
          command: make deploy
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
