name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  commit-watch:
    name: Run Commit Watch
    runs-on: ubuntu-20.04
    if: "github.event_name == 'pull_request' && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
        - uses: actions/checkout@v3.0.2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
            fetch-depth: 0
        - uses: ./.github/actions/setup-env
        - name: Run Commit Watch
          env:
            COMMIT_WATCH_OUTPUT_DIR: ${{ env.ARTIFACT_DIR }}/
            COMMITWATCH_GITHUB_TOKEN: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
            CI_REPO_OWNER: ${{ github.repository_owner }}
            CI_REPO_NAME: ${{ github.event.repository.name }}
            CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
            CI_BASE_BRANCH: origin/${{ github.base_ref }}
          run: yarn dlx commit-watch
        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: commit-watch-artifacts
            path: ${{ env.ARTIFACT_DIR }}
  tests:
    name: Lint, Tests, and Build
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
        - uses: actions/checkout@v3.0.2
          with:
            fetch-depth: 0
        - uses: ./.github/actions/setup-env
        - name: Linting
          run: yarn lint:ci
        - name: Tests
          run: yarn test:ci
        - name: Upload Coverage Report
          run: ./.github/codecov.sh $GITHUB_EVENT_PATH
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: reports-and-build-artifacts
            path: ${{ env.ARTIFACT_DIR }}
