name: Continuous Integration

on:
  - pull_request_target

env:
  CI: 1
  ARTIFACT_DIR: artifacts

jobs:
  tests:
    name: Lint, Tests, and Build
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v1
        - uses: ./.github/actions/detect-node
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: Restore node_modules Cache
          id: cache-node-modules
          uses: actions/cache@v2
          with:
            path: node_modules
            key: ${{ env.NODE_VERSION }}-${{ env.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
        - name: Install node_modules
          if: steps.cache-node-modules.outputs.cache-hit != 'true'
          run: yarn install --frozen-lockfile
        - name: Linting
          run: yarn lint
        - name: Tests
          run: yarn test
        - name: Build
          run: yarn build
        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: reports-and-build-artifacts
            path: ${{ env.ARTIFACT_DIR }}
