name: Package Release

on:
  workflow_dispatch:

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  release:
    name: Publish Packages
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v3.1.0
          with:
            token: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
            fetch-depth: 0
        - uses: ./.github/actions/setup-env
        - name: Publish Package (Pre-release)
          if: github.ref == 'refs/heads/next'
          env:
            NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
            GH_TOKEN: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
          run: |
            yarn monodeploy \
              --log-level 0 \
              --push \
              --changeset-ignore-patterns '**/*.test.ts' \
              --conventional-changelog-config @tophat/conventional-changelog-config \
              --prerelease
        - name: Publish Package
          id: publish
          if: github.ref == 'refs/heads/main'
          env:
            NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
            GH_TOKEN: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
          run: |
            yarn monodeploy \
              --log-level 0 \
              --plugins @monodeploy/plugin-github \
              --push \
              --changeset-ignore-patterns '**/*.test.ts' \
              --conventional-changelog-config @tophat/conventional-changelog-config \
              --auto-commit \
              --auto-commit-message "chore: release [skip ci]" \
              --changelog-filename "<packageDir>/CHANGELOG.md" \
              --persist-versions
        - name: Upload Artifacts
          if: ${{ always() }}
          uses: actions/upload-artifact@v3
          with:
            name: reports-and-build-artifacts
            path: |
                ${{ env.ARTIFACT_DIR }}
  website:
    name: Website
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    needs: [release]
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          token: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/actions/setup-env
      - name: Build & Deploy Website
        run: |
          git checkout gh-pages
          git reset --hard main
          yarn docs
          git add docs
          git commit -m "chore: update website" -n
          git push --force origin gh-pages
