name: Package Release

on:
  workflow_dispatch:

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  release:
    name: Publish commit-utils
    runs-on: ubuntu-20.04
    needs: [tests]
    if: "github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
        - uses: actions/checkout@v3
          with:
            token: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
            fetch-depth: 0
        - uses: ./.github/actions/detect-env
        - name: Setup Node.js
          uses: actions/setup-node@v3.1.1
          with:
            node-version: ${{ env.NODE_VERSION }}
        - name: Create artifacts directory
          run: mkdir -p ${{ env.ARTIFACT_DIR }}
        - name: Restore yarn cache
          id: yarn-cache
          uses: actions/cache@v2
          with:
            path: ./.yarn/cache
            key: ${{ env.NODE_VERSION }}-${{ env.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
        - name: Install dependencies
          run: yarn install --immutable
        - name: Configure Git
          run: |
            git config --global user.email opensource-leads+bot@tophatmonocle.com
            git config --global user.name tophat-opensource-bot
            git config --global init.defaultBranch master
        - name: Publish Package
          id: publish
          env:
            NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
            GH_TOKEN: ${{ secrets.TOPHAT_BOT_GH_TOKEN }}
          run: |
            yarn monodeploy --log-level 0 --plugins @monodeploy/plugin-github --config-file monodeploy.config.js
        - name: Upload Artifacts
          if: ${{ always() }}
          uses: actions/upload-artifact@v2
          with:
            name: reports-and-build-artifacts
            path: |
                ${{ env.ARTIFACT_DIR }}
